### ISSUE TITLE
versions 1.2.2 and 1.2.4 cause crash on game launch.

### ISSUE THREAD

**Issue by h4uja2** [notpeelz/reshade-xhair#1]
But 1.2.1 and previous work fine. Any ideas?

**Comment by notpeelz** [comment]
Have you tried renaming `dxgi.dll` to `d3d11.dll`?
What game are you using it for?

**Comment by h4uja2** [comment]
I'm on dx9, hl2

**Comment by notpeelz** [comment]
Seems to work fine on my end.
Are you using the recommended ReShade version (3.4.1)?

I installed it by selecting `hl2.exe` in `steamapps\common\Half-Life 2`, then moved `d3d9.dll` and `d3d9.ini` to the `bin` folder.

Weirdly enough, the crosshair seems to be much thicker than it should be. Not sure why.

Could you upload your `d3d9.log` file?

**Comment by h4uja2** [comment]
No, I'm on 4.2.1. Tried 3.4.1 and it does work fine there. There is nothing in the .log it just ends before xhair.fx is loaded.

So it doesn't support reshader 4.x ?

**Comment by notpeelz** [comment]
Yeah, ReShade 4.x isn't supported (yet). Unfortunately, 4.x isn't backwards-compatible :/

**Comment by notpeelz** [comment]
I pushed out an update to fix the crashing issue with ReShade 4. Let me know if that works for you :)
