### ISSUE TITLE
change RMB key to another button

### ISSUE THREAD

**Issue by P-Nam** [notpeelz/reshade-xhair#14]
i use Spacebar for scope, can i change RMB to Spacebar button to disable crosshair and where to do it.
Thank u

**Comment by notpeelz** [comment]
Change
```glsl
uniform bool rightMouseDown <
  source = "mousebutton";
  keycode = 1;
  toggle = false;
>;
```
to
```glsl
uniform bool rightMouseDown <
  source = "key";
  keycode = 0x20;
  mode = "";
>;
```

on [line 301](https://github.com/notpeelz/reshade-xhair/blob/96a6fddc0933b18705e96dda38b7f4936478a3b0/shaders/xhair.fx#L301).

**Comment by P-Nam** [comment]
successfully, thank u very much
