### ISSUE TITLE
Is it possible to have 2 crosshairs and right click to switch between? 

### ISSUE THREAD

**Issue by INeedABetterName2** [notpeelz/reshade-xhair#15]
Trying to make the default one my hip-fire crosshair and the other one for my scope reticle.

**Comment by notpeelz** [comment]
I don't see a way to easily add that as setting. However, you can use two xhair shaders as a workaround:

1. Open the folder containing the shader

![image](https://user-images.githubusercontent.com/920910/155861917-83a5aa81-b3f8-4731-9d94-c785b4e8ec63.png)

2. Duplicate the file and name it `xhair2.fx`
3. Open the new file in a text editor
4. Add `!` in front of `XOR` (currently line 509 on the latest version):

```diff
float4 PS_Xhair(float4 pos : SV_Position, float2 texcoord : TEXCOORD) : SV_Targe
   float4 drawBackground = tex2D(ReShade::BackBuffer, texcoord);
 
   // Don't render if RMB hiding is activated
-  if (XOR(HideOnRMB == 0 && rightMouseDown || HideOnRMB == 1 && rightMouseToggle, InvertHideOnRMB)) {
+  if (!XOR(HideOnRMB == 0 && rightMouseDown || HideOnRMB == 1 && rightMouseToggle, InvertHideOnRMB)) {
     return drawBackground;
   }
```

This will invert the behavior of the "Hide on RMB" setting.

**Comment by INeedABetterName2** [comment]
It worked, Thank you so much. :D

**Comment by notpeelz** [comment]
You're welcome :D
