### ISSUE TITLE
Independent controls for 2 crosshairs

### ISSUE THREAD

**Issue by assist726** [notpeelz/reshade-xhair#16]
https://github.com/notpeelz/reshade-xhair/issues/15

I've seen this past issue and have been able to setup 2 sets of crosshairs. However it seems that just renaming the xhair file alone wouldn't separate controls for them completely, the Toggle hotkey and remember on/off state on game startup can't be mapped separately.

Would appreciate if I could get some advice on how I might need to rename within the file to seperate these two completely?

@notpeelz

**Comment by notpeelz** [comment]
Did you apply the changes I suggested in https://github.com/notpeelz/reshade-xhair/issues/15#issuecomment-1052829193 ?

> the Toggle hotkey and remember on/off state on game startup can't be mapped separately.

Are you talking about the "Effect toggle key"?
![image](https://user-images.githubusercontent.com/920910/182248789-9a0465db-fb48-449d-acb0-0ec961dc8da2.png)
This is a global keybind and it doesn't actually disable anything persistently. Once you restart your game, the settings will be the same as they were before. It's meant as a quick on/off switch for toggling all your shaders.

There's also a (persistent) per-shader toggle bind (right click on the shader):
![image](https://user-images.githubusercontent.com/920910/182249077-11be85ff-2ff8-4f35-8cd9-24dbd7f4bf63.png)
Maybe this is what you're looking for?
Can you clarify what you're expecting?

**Comment by assist726** [comment]
Thanks for the clarifying screenshots, I was talking about the per shader toggle bind not the global. 
But as I was saying copying and pasting the file and only renaming the filename results in the per shader toggle bind shortcut being forced to be the same key. If I edit xhair1's toggle key after it saving xhair2 will result in the same key. I can only assume right now without changing the variables in file reshade is treating the 2 xhairs as 1 item.

The effect I'm looking for is having independent hotkeys for each so that I can keep xhair1 on whilst toggling xhair2.

**Comment by notpeelz** [comment]
Just to make sure I understand correctly: you want two different keys to toggle xhair1 and xhair2 independently of each other?
FYI those binds are a ReShade feature ([not my code](https://github.com/crosire/reshade)), so if you encounter a bug with them, there's not much I can do to fix that.
What version of ReShade are you on? Try upgrading if you're not already on the latest version.

**Comment by notpeelz** [comment]
I just tested and it seems to work fine for me

![image](https://user-images.githubusercontent.com/920910/182288091-fb3adee4-0a41-46bf-bce6-d5ba29deee22.png)

https://user-images.githubusercontent.com/920910/182287898-8c9a6630-b57f-464f-9c4c-3adbf4d18c17.mp4

**Comment by assist726** [comment]
@notpeelz Thanks for the help! I played around with reshade a bit more and it appears it's my fault that I changed to performance mode and when editing settings it never actually saved, I switched back to Configuration mode and all is good now!

**Comment by notpeelz** [comment]
Ah yeah, that would make sense. I forgot about performance mode. Glad you got it sorted out.
