### ISSUE TITLE
Toggle for xHair

### ISSUE THREAD

**Issue by Stefcrash** [notpeelz/reshade-xhair#17]
Is there any way to have the crosshair turned off by default and whenever I right click, the crosshair should appear.
So I toggle it while hold.

If I see right, at the moment there is only an option for the crosshair to be permanently visible and while holding right click it disappears.

**Comment by notpeelz** [comment]
ReShade has a feature to toggle shaders using hotkeys. Have you looked into that?

**Comment by notpeelz** [comment]
Ah, I misunderstood what you said. What you're describing is the behavior of the "Invert Hide on RMB" setting.
