### ISSUE TITLE
Crashes on Dead by Daylight

### ISSUE THREAD

**Issue by LilLovebird** [notpeelz/reshade-xhair#19]
Might be a ReShade issue but I've never had this problem until after installing this.
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000010

**Comment by notpeelz** [comment]
It's definitely a problem with ReShade.

Seems like some people were able to work around that crash by launching DBD with DX12:
https://old.reddit.com/r/ReShade/comments/13tdysp/dead_by_daylight_reshade_makes_game_crash/
