### ISSUE TITLE
Origin Overlay disabled?

### ISSUE THREAD

**Issue by LichKnightSena** [notpeelz/reshade-xhair#2]
Since I installed the mod, My origin Overlay doesn't want to come up, Could someone help me resolve this issue? I cant accept or Make origin invites

**Comment by notpeelz** [comment]
The default ReShade overlay shortcut is Shift-F2 (and so is Origin's). You're gonna have to rebind one of them.
![image](https://user-images.githubusercontent.com/920910/62837025-3b43cb80-bc38-11e9-9734-50261f5327b8.png)

**Comment by LichKnightSena** [comment]
I did this and The origin Still doesn't come up Sorry for the late Reply!

**Comment by LichKnightSena** [comment]
Is there any way I could come into contact with you easier Like Discord or even emails?

**Comment by Orhtej** [comment]
Sorry for necroing, but I have the same issue. Changing keybind doesn't do anything. I can't add and accept invites, also can't purchase things.

**Comment by notpeelz** [comment]
Hmm, unfortunately I can't do anything about it. This is a ReShade issue :/
The issue might be fixed in ReShade 4.x. I could try updating the shader code so that it's compatible with later versions.

Could you test if ReShade 4 has the same issue? (without the shader obviously)
