### ISSUE TITLE
can i change the hide on rmb for appear on rmb?

### ISSUE THREAD

**Issue by Rxzkkj** [notpeelz/reshade-xhair#20]
can i change the hide on rmb for appear on rmb? i aim with the rmb and the xhair desapears when i click it

**Comment by notpeelz** [comment]
Use the "Invert Hide on RMB" setting.

**Comment by Rxzkkj** [comment]
u have some footage or tutorial how to do it? sry im dont know about this things

**Comment by notpeelz** [comment]
"Invert Hide on RMB" should be directly below the "Hide on RMB" setting.
If you can't see it, then you might be using an outdated version.
