### ISSUE TITLE
Can we change the toggle key for the crosshair?

### ISSUE THREAD

**Issue by Au-x-In** [notpeelz/reshade-xhair#22]
I recently installed your Crosshair add-on for Dead by Daylight and I like it very much, but the right mouse button is essential for many killers and turning it on and off all the time can be annoying or just doesn't help. 
I already tried to look through your code to maybe find a way to change the key that the Program looks for but I had no success. 
Is there any way, or can this be added?

I look forward to a reply, thank you.

**Comment by notpeelz** [comment]
Did you try setting HideOnRMB to "Disabled"?

**Comment by Au-x-In** [comment]
Yes, i already experimented with that, but then it is always on but it would be nice to toggle on each shader loadout to just juse when i use a killer that i wish to use it on (where i need it).
It's mostly a problem of it just being easier to use (turn on and off)

_Edit:
I looked through your code a little bit, but all I can find that is connected to this feature makes sense but doesn't have an impact on which button press is registered and I didn't want to fiddle with your code too much, also because I have really not much of an idea how that language works or what i should do_

**Comment by notpeelz** [comment]
You can assign a toggle hotkey by right-clicking the shader in the list (it's a feature built into ReShade).
You can also assign hotkeys to cycle through presets; it's located under the settings tab.

**Comment by Au-x-In** [comment]
Alright i totally overlooked that feature, i didn't know it could be used for that kind of stuff. 
I just set the 'HideOnRMB' on "dissabled" and set a toggle key for 'invert action of RMB' so essentialy i have it exacly like i need it.
Thx for the help.
