### ISSUE TITLE
Outline and button to hide

### ISSUE THREAD

**Issue by Parandreu** [notpeelz/reshade-xhair#4]
Hi,
The inside of the cross has no outline and the outline is wider in the edges. https://i.imgur.com/IBgEOcA.png
And less important, the dot does not have outline either.
Some other button to hide during the cinematics, like F2. I would be very grateful.

**Comment by notpeelz** [comment]
Hey. I don't have any plans to add inner/dot outlines at the moment.
You should be able to set a toggle key for the shader (it's a built-in ReShade feature).

**Comment by Parandreu** [comment]
Hi,
I don't know how to do the toggle key thing but I don't want to waste your time, thanks for answering.

**Comment by notpeelz** [comment]
No problem at all. Assuming that you're on ReShade 4.x, you should be able to set it by right-clicking the shader.
![image](https://user-images.githubusercontent.com/920910/74272879-65587200-4cdd-11ea-90ff-f339a3918994.png)

**Comment by Parandreu** [comment]
Sorry, is the first time I use ReShade, that works, thank you very much.

I no longer use the dot, and I guess the inner outline is something minor, I close the issue. Thanks again.

**Comment by notpeelz** [comment]
No problem. If you want a dot with an outline, you can always use a circle crosshair with no gap.
